# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users:
                    mrgreen :
                        password: mrgreen
                        roles: 'ROLE_GREEN'
                    mrblue :
                        password: mrblue
                        roles: 'ROLE_BLUE'
                    mryellow :
                        password: mryellow
                        roles: 'ROLE_YELLOW'
                    mrred :
                        password: mrred
                        roles: 'ROLE_RED'
                    
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    
    
                        
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

#            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                check_path: /loginCheck
                login_path: /login
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            logout:
                path: /logout
                target: /blue
            
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/green, roles: ROLE_GREEN }
        - { path: ^/blue, roles: ROLE_BLUE }
        - { path: ^/yellow, roles: ROLE_YELLOW }
        - { path: ^/red, roles: ROLE_RED }
